# Generated by Django 4.2.13 on 2024-06-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exe_file',
            field=models.FileField(blank=True, upload_to='project_downloads'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
