# Generated by Django 4.2.13 on 2024-06-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_video_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
